// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: accesslogic.proto
#ifndef GRPC_accesslogic_2eproto__INCLUDED
#define GRPC_accesslogic_2eproto__INCLUDED

#include "accesslogic.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace accesslogic {

class AccessLogicService final {
 public:
  static constexpr char const* service_full_name() {
    return "accesslogic.AccessLogicService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Hello(::grpc::ClientContext* context, const ::accesslogic::HelloReq& request, ::accesslogic::HelloResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::accesslogic::HelloResp>> AsyncHello(::grpc::ClientContext* context, const ::accesslogic::HelloReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::accesslogic::HelloResp>>(AsyncHelloRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::accesslogic::HelloResp>> PrepareAsyncHello(::grpc::ClientContext* context, const ::accesslogic::HelloReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::accesslogic::HelloResp>>(PrepareAsyncHelloRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void Hello(::grpc::ClientContext* context, const ::accesslogic::HelloReq* request, ::accesslogic::HelloResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Hello(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::accesslogic::HelloResp* response, std::function<void(::grpc::Status)>) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::accesslogic::HelloResp>* AsyncHelloRaw(::grpc::ClientContext* context, const ::accesslogic::HelloReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::accesslogic::HelloResp>* PrepareAsyncHelloRaw(::grpc::ClientContext* context, const ::accesslogic::HelloReq& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Hello(::grpc::ClientContext* context, const ::accesslogic::HelloReq& request, ::accesslogic::HelloResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::accesslogic::HelloResp>> AsyncHello(::grpc::ClientContext* context, const ::accesslogic::HelloReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::accesslogic::HelloResp>>(AsyncHelloRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::accesslogic::HelloResp>> PrepareAsyncHello(::grpc::ClientContext* context, const ::accesslogic::HelloReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::accesslogic::HelloResp>>(PrepareAsyncHelloRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void Hello(::grpc::ClientContext* context, const ::accesslogic::HelloReq* request, ::accesslogic::HelloResp* response, std::function<void(::grpc::Status)>) override;
      void Hello(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::accesslogic::HelloResp* response, std::function<void(::grpc::Status)>) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::accesslogic::HelloResp>* AsyncHelloRaw(::grpc::ClientContext* context, const ::accesslogic::HelloReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::accesslogic::HelloResp>* PrepareAsyncHelloRaw(::grpc::ClientContext* context, const ::accesslogic::HelloReq& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Hello_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Hello(::grpc::ServerContext* context, const ::accesslogic::HelloReq* request, ::accesslogic::HelloResp* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Hello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_Hello() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Hello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Hello(::grpc::ServerContext* context, const ::accesslogic::HelloReq* request, ::accesslogic::HelloResp* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHello(::grpc::ServerContext* context, ::accesslogic::HelloReq* request, ::grpc::ServerAsyncResponseWriter< ::accesslogic::HelloResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Hello<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_Hello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_Hello() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::accesslogic::HelloReq, ::accesslogic::HelloResp>(
          [this](::grpc::ServerContext* context,
                 const ::accesslogic::HelloReq* request,
                 ::accesslogic::HelloResp* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->Hello(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithCallbackMethod_Hello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Hello(::grpc::ServerContext* context, const ::accesslogic::HelloReq* request, ::accesslogic::HelloResp* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void Hello(::grpc::ServerContext* context, const ::accesslogic::HelloReq* request, ::accesslogic::HelloResp* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_Hello<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Hello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_Hello() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Hello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Hello(::grpc::ServerContext* context, const ::accesslogic::HelloReq* request, ::accesslogic::HelloResp* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Hello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_Hello() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Hello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Hello(::grpc::ServerContext* context, const ::accesslogic::HelloReq* request, ::accesslogic::HelloResp* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHello(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_Hello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_Hello() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->Hello(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_Hello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Hello(::grpc::ServerContext* context, const ::accesslogic::HelloReq* request, ::accesslogic::HelloResp* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void Hello(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Hello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_Hello() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::accesslogic::HelloReq, ::accesslogic::HelloResp>(std::bind(&WithStreamedUnaryMethod_Hello<BaseClass>::StreamedHello, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_Hello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Hello(::grpc::ServerContext* context, const ::accesslogic::HelloReq* request, ::accesslogic::HelloResp* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedHello(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::accesslogic::HelloReq,::accesslogic::HelloResp>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Hello<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Hello<Service > StreamedService;
};

}  // namespace accesslogic


#endif  // GRPC_accesslogic_2eproto__INCLUDED
