// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: accesslogic.proto

#include "accesslogic.pb.h"
#include "accesslogic.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace accesslogic {

static const char* AccessLogicService_method_names[] = {
  "/accesslogic.AccessLogicService/Hello",
};

std::unique_ptr< AccessLogicService::Stub> AccessLogicService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< AccessLogicService::Stub> stub(new AccessLogicService::Stub(channel));
  return stub;
}

AccessLogicService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Hello_(AccessLogicService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status AccessLogicService::Stub::Hello(::grpc::ClientContext* context, const ::accesslogic::HelloReq& request, ::accesslogic::HelloResp* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Hello_, context, request, response);
}

void AccessLogicService::Stub::experimental_async::Hello(::grpc::ClientContext* context, const ::accesslogic::HelloReq* request, ::accesslogic::HelloResp* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Hello_, context, request, response, std::move(f));
}

void AccessLogicService::Stub::experimental_async::Hello(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::accesslogic::HelloResp* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Hello_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::accesslogic::HelloResp>* AccessLogicService::Stub::AsyncHelloRaw(::grpc::ClientContext* context, const ::accesslogic::HelloReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::accesslogic::HelloResp>::Create(channel_.get(), cq, rpcmethod_Hello_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::accesslogic::HelloResp>* AccessLogicService::Stub::PrepareAsyncHelloRaw(::grpc::ClientContext* context, const ::accesslogic::HelloReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::accesslogic::HelloResp>::Create(channel_.get(), cq, rpcmethod_Hello_, context, request, false);
}

AccessLogicService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AccessLogicService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AccessLogicService::Service, ::accesslogic::HelloReq, ::accesslogic::HelloResp>(
          std::mem_fn(&AccessLogicService::Service::Hello), this)));
}

AccessLogicService::Service::~Service() {
}

::grpc::Status AccessLogicService::Service::Hello(::grpc::ServerContext* context, const ::accesslogic::HelloReq* request, ::accesslogic::HelloResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace accesslogic

